/**
 * UI icon set: Microsoft Fluent Emoji 3D (MIT). One visual family for the whole app.
 * See assets/ui/icons/LICENSE.md. Add a PNG to assets/ui/icons and register it here.
 */
export const ICONS = {
  baby: require('../../assets/ui/icons/baby.png'),
  banana: require('../../assets/ui/icons/banana.png'),
  beach: require('../../assets/ui/icons/beach.png'),
  beetle: require('../../assets/ui/icons/beetle.png'),
  blossom: require('../../assets/ui/icons/blossom.png'),
  books: require('../../assets/ui/icons/books.png'),
  bowl: require('../../assets/ui/icons/bowl.png'),
  bug: require('../../assets/ui/icons/bug.png'),
  camera: require('../../assets/ui/icons/camera.png'),
  carrot: require('../../assets/ui/icons/carrot.png'),
  check: require('../../assets/ui/icons/check.png'),
  cherry: require('../../assets/ui/icons/cherry.png'),
  city: require('../../assets/ui/icons/city.png'),
  corn: require('../../assets/ui/icons/corn.png'),
  crab: require('../../assets/ui/icons/crab.png'),
  dash: require('../../assets/ui/icons/dash.png'),
  desert: require('../../assets/ui/icons/desert.png'),
  dove: require('../../assets/ui/icons/dove.png'),
  earth: require('../../assets/ui/icons/earth.png'),
  egg: require('../../assets/ui/icons/egg.png'),
  feather: require('../../assets/ui/icons/feather.png'),
  fish: require('../../assets/ui/icons/fish.png'),
  footprints: require('../../assets/ui/icons/footprints.png'),
  gear: require('../../assets/ui/icons/gear.png'),
  glowing: require('../../assets/ui/icons/glowing.png'),
  hay: require('../../assets/ui/icons/hay.png'),
  heart: require('../../assets/ui/icons/heart.png'),
  herb: require('../../assets/ui/icons/herb.png'),
  hippo: require('../../assets/ui/icons/hippo.png'),
  house: require('../../assets/ui/icons/house.png'),
  kangaroo: require('../../assets/ui/icons/kangaroo.png'),
  leaves: require('../../assets/ui/icons/leaves.png'),
  lizard: require('../../assets/ui/icons/lizard.png'),
  lock: require('../../assets/ui/icons/lock.png'),
  lotus: require('../../assets/ui/icons/lotus.png'),
  magnifier: require('../../assets/ui/icons/magnifier.png'),
  meat: require('../../assets/ui/icons/meat.png'),
  mountain: require('../../assets/ui/icons/mountain.png'),
  park: require('../../assets/ui/icons/park.png'),
  party: require('../../assets/ui/icons/party.png'),
  paws: require('../../assets/ui/icons/paws.png'),
  peanuts: require('../../assets/ui/icons/peanuts.png'),
  puzzle: require('../../assets/ui/icons/puzzle.png'),
  seedling: require('../../assets/ui/icons/seedling.png'),
  shrimp: require('../../assets/ui/icons/shrimp.png'),
  sloth: require('../../assets/ui/icons/sloth.png'),
  snake: require('../../assets/ui/icons/snake.png'),
  sparkles: require('../../assets/ui/icons/sparkles.png'),
  speaker: require('../../assets/ui/icons/speaker.png'),
  squid: require('../../assets/ui/icons/squid.png'),
  star: require('../../assets/ui/icons/star.png'),
  sunflower: require('../../assets/ui/icons/sunflower.png'),
  sunrise: require('../../assets/ui/icons/sunrise.png'),
  swimming: require('../../assets/ui/icons/swimming.png'),
  teddy: require('../../assets/ui/icons/teddy.png'),
  tractor: require('../../assets/ui/icons/tractor.png'),
  tree: require('../../assets/ui/icons/tree.png'),
  trophy: require('../../assets/ui/icons/trophy.png'),
  wave: require('../../assets/ui/icons/wave.png'),
  wing: require('../../assets/ui/icons/wing.png'),
  wood: require('../../assets/ui/icons/wood.png'),
  worm: require('../../assets/ui/icons/worm.png'),
  yarn: require('../../assets/ui/icons/yarn.png'),
} as const;

export type IconName = keyof typeof ICONS;
