// AUTO-GENERATED by `npm run assets:registry` from content/animals/legacy-seed.json.
// Do not edit by hand.
import type { AnimalMediaModules } from './media';

export const ANIMAL_MEDIA: Record<string, AnimalMediaModules> = {
  bear: {
    image: require('../../assets/animals/art/bear.png'),
    sound: require('../../assets/animals/sounds/bear.mp3'),
    nameAudio: require('../../assets/animals/names/bear_name.mp3'),
    model3d: require('../../assets/animals/models/bear.glb'),
  },
  bee: {
    image: require('../../assets/animals/art/bee.png'),
    sound: require('../../assets/animals/sounds/bee.mp3'),
    nameAudio: require('../../assets/animals/names/bee_name.mp3'),
    model3d: require('../../assets/animals/models/bee.glb'),
  },
  cat: {
    image: require('../../assets/animals/art/cat.png'),
    sound: require('../../assets/animals/sounds/cat.mp3'),
    nameAudio: require('../../assets/animals/names/cat_name.mp3'),
    model3d: require('../../assets/animals/models/cat.glb'),
  },
  chick: {
    image: require('../../assets/animals/art/chick.png'),
    sound: require('../../assets/animals/sounds/chick.mp3'),
    nameAudio: require('../../assets/animals/names/chick_name.mp3'),
    model3d: require('../../assets/animals/models/chick.glb'),
  },
  chicken: {
    image: require('../../assets/animals/art/chicken.png'),
    sound: require('../../assets/animals/sounds/chicken.mp3'),
    nameAudio: require('../../assets/animals/names/chicken_name.mp3'),
    model3d: require('../../assets/animals/models/chicken.glb'),
  },
  cock: {
    image: require('../../assets/animals/art/cock.png'),
    sound: require('../../assets/animals/sounds/cock.mp3'),
    nameAudio: require('../../assets/animals/names/cock_name.mp3'),
    model3d: require('../../assets/animals/models/cock.glb'),
  },
  cow: {
    image: require('../../assets/animals/art/cow.png'),
    sound: require('../../assets/animals/sounds/cow.mp3'),
    nameAudio: require('../../assets/animals/names/cow_name.mp3'),
    model3d: require('../../assets/animals/models/cow.glb'),
  },
  dog: {
    image: require('../../assets/animals/art/dog.png'),
    sound: require('../../assets/animals/sounds/dog.mp3'),
    nameAudio: require('../../assets/animals/names/dog_name.mp3'),
    model3d: require('../../assets/animals/models/dog.glb'),
  },
  dolphin: {
    image: require('../../assets/animals/art/dolphin.png'),
    sound: require('../../assets/animals/sounds/dolphin.mp3'),
    nameAudio: require('../../assets/animals/names/dolphin_name.mp3'),
    model3d: require('../../assets/animals/models/dolphin.glb'),
  },
  duck: {
    image: require('../../assets/animals/art/duck.png'),
    sound: require('../../assets/animals/sounds/duck.mp3'),
    nameAudio: require('../../assets/animals/names/duck_name.mp3'),
    model3d: require('../../assets/animals/models/duck.glb'),
  },
  elephant: {
    image: require('../../assets/animals/art/elephant.png'),
    sound: require('../../assets/animals/sounds/elephant.mp3'),
    nameAudio: require('../../assets/animals/names/elephant_name.mp3'),
    model3d: require('../../assets/animals/models/elephant.glb'),
  },
  frog: {
    image: require('../../assets/animals/art/frog.png'),
    sound: require('../../assets/animals/sounds/frog.mp3'),
    nameAudio: require('../../assets/animals/names/frog_name.mp3'),
    model3d: require('../../assets/animals/models/frog.glb'),
  },
  horse: {
    image: require('../../assets/animals/art/horse.png'),
    sound: require('../../assets/animals/sounds/horse.mp3'),
    nameAudio: require('../../assets/animals/names/horse_name.mp3'),
    model3d: require('../../assets/animals/models/horse.glb'),
  },
  lion: {
    image: require('../../assets/animals/art/lion.png'),
    sound: require('../../assets/animals/sounds/lion.mp3'),
    nameAudio: require('../../assets/animals/names/lion_name.mp3'),
    model3d: require('../../assets/animals/models/lion.glb'),
  },
  monkey: {
    image: require('../../assets/animals/art/monkey.png'),
    sound: require('../../assets/animals/sounds/monkey.mp3'),
    nameAudio: require('../../assets/animals/names/monkey_name.mp3'),
    model3d: require('../../assets/animals/models/monkey.glb'),
  },
  parrot: {
    image: require('../../assets/animals/art/parrot.png'),
    sound: require('../../assets/animals/sounds/parrot.mp3'),
    nameAudio: require('../../assets/animals/names/parrot_name.mp3'),
    model3d: require('../../assets/animals/models/parrot.glb'),
  },
  pig: {
    image: require('../../assets/animals/art/pig.png'),
    sound: require('../../assets/animals/sounds/pig.mp3'),
    nameAudio: require('../../assets/animals/names/pig_name.mp3'),
    model3d: require('../../assets/animals/models/pig.glb'),
  },
  seal: {
    image: require('../../assets/animals/art/seal.png'),
    sound: require('../../assets/animals/sounds/seal.mp3'),
    nameAudio: require('../../assets/animals/names/seal_name.mp3'),
    model3d: require('../../assets/animals/models/seal.glb'),
  },
  sheep: {
    image: require('../../assets/animals/art/sheep.png'),
    sound: require('../../assets/animals/sounds/sheep.mp3'),
    nameAudio: require('../../assets/animals/names/sheep_name.mp3'),
    model3d: require('../../assets/animals/models/sheep.glb'),
  },
  tiger: {
    image: require('../../assets/animals/art/tiger.png'),
    sound: require('../../assets/animals/sounds/tiger.mp3'),
    nameAudio: require('../../assets/animals/names/tiger_name.mp3'),
    model3d: require('../../assets/animals/models/tiger.glb'),
  },
  turkey: {
    image: require('../../assets/animals/art/turkey.png'),
    sound: require('../../assets/animals/sounds/turkey.mp3'),
    nameAudio: require('../../assets/animals/names/turkey_name.mp3'),
    model3d: require('../../assets/animals/models/turkey.glb'),
  },
  wolf: {
    image: require('../../assets/animals/art/wolf.png'),
    sound: require('../../assets/animals/sounds/wolf.mp3'),
    nameAudio: require('../../assets/animals/names/wolf_name.mp3'),
    model3d: require('../../assets/animals/models/wolf.glb'),
  },
};
