// AUTO-GENERATED by `npm run assets:registry` from content/animals/legacy-seed.json.
// Do not edit by hand.
import type { AnimalMediaModules } from './media';

export const ANIMAL_MEDIA: Record<string, AnimalMediaModules> = {
  bear: {
    image: require('../../assets/animals/images/bear.png'),
    sound: require('../../assets/animals/sounds/bear.mp3'),
    nameAudio: require('../../assets/animals/names/bear_name.mp3'),
    model3d: null,
  },
  bee: {
    image: require('../../assets/animals/art/bee.png'),
    sound: require('../../assets/animals/sounds/bee.mp3'),
    nameAudio: require('../../assets/animals/names/bee_name.mp3'),
    model3d: null,
  },
  cat: {
    image: require('../../assets/animals/images/cat.png'),
    sound: require('../../assets/animals/sounds/cat.mp3'),
    nameAudio: require('../../assets/animals/names/cat_name.mp3'),
    model3d: null,
  },
  chick: {
    image: require('../../assets/animals/images/chick.png'),
    sound: require('../../assets/animals/sounds/chick.mp3'),
    nameAudio: require('../../assets/animals/names/chick_name.mp3'),
    model3d: null,
  },
  chicken: {
    image: require('../../assets/animals/art/chicken.png'),
    sound: require('../../assets/animals/sounds/chicken.mp3'),
    nameAudio: require('../../assets/animals/names/chicken_name.mp3'),
    model3d: null,
  },
  cock: {
    image: require('../../assets/animals/images/cock.png'),
    sound: require('../../assets/animals/sounds/cock.mp3'),
    nameAudio: require('../../assets/animals/names/cock_name.mp3'),
    model3d: null,
  },
  cow: {
    image: require('../../assets/animals/images/cow.png'),
    sound: require('../../assets/animals/sounds/cow.mp3'),
    nameAudio: require('../../assets/animals/names/cow_name.mp3'),
    model3d: null,
  },
  dog: {
    image: require('../../assets/animals/art/dog.png'),
    sound: require('../../assets/animals/sounds/dog.mp3'),
    nameAudio: require('../../assets/animals/names/dog_name.mp3'),
    model3d: null,
  },
  dolphin: {
    image: require('../../assets/animals/images/dolphin.png'),
    sound: require('../../assets/animals/sounds/dolphin.mp3'),
    nameAudio: require('../../assets/animals/names/dolphin_name.mp3'),
    model3d: null,
  },
  duck: {
    image: require('../../assets/animals/images/duck.png'),
    sound: require('../../assets/animals/sounds/duck.mp3'),
    nameAudio: require('../../assets/animals/names/duck_name.mp3'),
    model3d: null,
  },
  elephant: {
    image: require('../../assets/animals/art/elephant.png'),
    sound: require('../../assets/animals/sounds/elephant.mp3'),
    nameAudio: require('../../assets/animals/names/elephant_name.mp3'),
    model3d: null,
  },
  frog: {
    image: require('../../assets/animals/images/frog.png'),
    sound: require('../../assets/animals/sounds/frog.mp3'),
    nameAudio: require('../../assets/animals/names/frog_name.mp3'),
    model3d: null,
  },
  horse: {
    image: require('../../assets/animals/images/horse.png'),
    sound: require('../../assets/animals/sounds/horse.mp3'),
    nameAudio: require('../../assets/animals/names/horse_name.mp3'),
    model3d: null,
  },
  lion: {
    image: require('../../assets/animals/images/lion.png'),
    sound: require('../../assets/animals/sounds/lion.mp3'),
    nameAudio: require('../../assets/animals/names/lion_name.mp3'),
    model3d: null,
  },
  monkey: {
    image: require('../../assets/animals/images/monkey.png'),
    sound: require('../../assets/animals/sounds/monkey.mp3'),
    nameAudio: require('../../assets/animals/names/monkey_name.mp3'),
    model3d: null,
  },
  parrot: {
    image: require('../../assets/animals/images/parrot.png'),
    sound: require('../../assets/animals/sounds/parrot.mp3'),
    nameAudio: require('../../assets/animals/names/parrot_name.mp3'),
    model3d: null,
  },
  pig: {
    image: require('../../assets/animals/art/pig.png'),
    sound: require('../../assets/animals/sounds/pig.mp3'),
    nameAudio: require('../../assets/animals/names/pig_name.mp3'),
    model3d: null,
  },
  seal: {
    image: require('../../assets/animals/images/seal.png'),
    sound: require('../../assets/animals/sounds/seal.mp3'),
    nameAudio: require('../../assets/animals/names/seal_name.mp3'),
    model3d: null,
  },
  sheep: {
    image: require('../../assets/animals/images/sheep.png'),
    sound: require('../../assets/animals/sounds/sheep.mp3'),
    nameAudio: require('../../assets/animals/names/sheep_name.mp3'),
    model3d: null,
  },
  tiger: {
    image: require('../../assets/animals/images/tiger.png'),
    sound: require('../../assets/animals/sounds/tiger.mp3'),
    nameAudio: require('../../assets/animals/names/tiger_name.mp3'),
    model3d: null,
  },
  turkey: {
    image: require('../../assets/animals/images/turkey.png'),
    sound: require('../../assets/animals/sounds/turkey.mp3'),
    nameAudio: require('../../assets/animals/names/turkey_name.mp3'),
    model3d: null,
  },
  wolf: {
    image: require('../../assets/animals/images/wolf.png'),
    sound: require('../../assets/animals/sounds/wolf.mp3'),
    nameAudio: require('../../assets/animals/names/wolf_name.mp3'),
    model3d: null,
  },
};
