import { readFileSync } from 'node:fs';

import { fromRoot } from './paths';

interface SeedAnimal {
  id: string;
  media: { image: string; sound: string; nameAudio: string; model3d?: string | null };
}

export const REGISTRY_PATH = 'src/content/media.generated.ts';

export function readSeedAnimals(): SeedAnimal[] {
  return JSON.parse(readFileSync(fromRoot('content/animals/legacy-seed.json'), 'utf8')).animals;
}

/** Metro only bundles static `require()` calls, so media paths are code-generated from the seed. */
export function renderRegistry(animals: SeedAnimal[]): string {
  const req = (p: string) => `require('../../${p}')`;
  const lines = animals
    .slice()
    .sort((a, b) => a.id.localeCompare(b.id))
    .map((a) => {
      const model = a.media.model3d ? req(a.media.model3d) : 'null';
      return [
        `  ${a.id}: {`,
        `    image: ${req(a.media.image)},`,
        `    sound: ${req(a.media.sound)},`,
        `    nameAudio: ${req(a.media.nameAudio)},`,
        `    model3d: ${model},`,
        `  },`,
      ].join('\n');
    });
  return [
    '// AUTO-GENERATED by `npm run assets:registry` from content/animals/legacy-seed.json.',
    '// Do not edit by hand.',
    "import type { AnimalMediaModules } from './media';",
    '',
    'export const ANIMAL_MEDIA: Record<string, AnimalMediaModules> = {',
    ...lines,
    '};',
    '',
  ].join('\n');
}
